[package]
name = "riscv-rt"
version = "0.9.0"
rust-version = "1.59"
repository = "https://github.com/rust-embedded/riscv-rt"
authors = ["The RISC-V Team <risc-v@teams.rust-embedded.org>"]
categories = ["embedded", "no-std"]
description = "Minimal runtime / startup for RISC-V CPU's"
keywords = ["riscv", "runtime", "startup"]
license = "ISC"
links = "riscv-rt" # prevent multiple versions of this crate to be linked together
edition = "2018"

[dependencies]
r0 = "1.0.0"
riscv = "0.8"
riscv-rt-macros = { path = "macros", version = "0.2.0" }

[dev-dependencies]
panic-halt = "0.2.0"
